route:
  receiver: telegram

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: "8206133908:AAH-b74AMCoXRAGo24ihGS9PZjtWEep3Zv4"
        chat_id: 1575883520
        message: |
          ðŸš¨ NSU AI Alert ðŸš¨
          {{ .CommonAnnotations.summary }}
